services:
  app:
    build: ./backend
    container_name: node_hubbi
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRESIN=${JWT_EXPIRESIN}
    depends_on:
      - db
    networks:
      - desafio-hubbi

  frontend:
    build: ./frontend
    container_name: node_frontend
    environment:
      - NEXT_PUBLIC_URL_API=${NEXT_PUBLIC_URL_API}
    ports:
      - "3000:3000"
    networks:
      - desafio-hubbi

  db:
    image: postgres:13
    container_name: postgres_hubbi
    environment:
      POSTGRES_USER: jadson
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: desafioHubbi
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - desafio-hubbi

networks:
  desafio-hubbi:

volumes:
  postgres-data:
