services:
  app:
    build: ./backend
    container_name: node_hubbi
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://jadson:1234@db:5432/desafioHubbi
      - JWT_SECRET=ynQ7pg2_AEuKm6ZeTy7OsvHD32a_4xr6e15v4EfESt4
      - JWT_EXPIRESIN=1d
    depends_on:
      - db
    networks:
      - desafio-hubbi

  frontend:
    build: ./frontend
    container_name: node_frontend
    environment:
      - NEXT_PUBLIC_URL_API="http://localhost:4000"
    ports:
      - "3000:3000"
    networks:
      - desafio-hubbi

  db:
    image: postgres:13
    container_name: postgres_hubbi
    environment:
      POSTGRES_USER: jadson
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: desafioHubbi
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - desafio-hubbi

networks:
  desafio-hubbi:

volumes:
  postgres-data:
